# Cloudflare Pages configuration
name = "wed-inv"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "wed-inv-db"
database_id = "7bc597bd-bfbb-438d-b6f1-29766bfc855e"
